// eslint.config.mjs
//
// `obsidianmd.configs.recommended` already bundles ESLint core recommended,
// typescript-eslint's type-checked rules and the Obsidian plugin rules used by
// the community plugin review, so none of those need to be added separately.

import { defineConfig, globalIgnores } from 'eslint/config';
import obsidianmd from 'eslint-plugin-obsidianmd';

export default defineConfig([
	globalIgnores([
		'dist/',
		// ESLint ignores `node_modules/` by default, but not this leftover copy.
		'node_modules.nosync/',
		// Generated by `npm run grammar` from src/grammar.pegjs; not hand-edited.
		'src/peggy.mjs',
		// The recommended config lints JSON (useful for manifest.json), but the
		// lockfile is large enough to exhaust the heap.
		'package-lock.json',
	]),
	...obsidianmd.configs.recommended,
	{
		// TypeScript itself resolves globals and imports, so `no-undef` only produces
		// false positives here (notably in the ambient declarations of src/types).
		files: ['**/*.ts'],
		rules: { 'no-undef': 'off' },
	},
	{
		// Build tooling that runs under Node, not inside Obsidian: the mobile-safety
		// rules about Node built-ins do not apply.
		files: ['*.mjs'],
		languageOptions: { globals: { process: 'readonly' } },
		rules: { 'obsidianmd/no-nodejs-modules': 'off' },
	},
	{
		languageOptions: {
			parserOptions: {
				// The build scripts and this file live outside tsconfig.json's `include`,
				// so the type-checked rules need permission to fall back for them.
				projectService: {
					allowDefaultProject: [
						'eslint.config.mjs',
						'esbuild.config.mjs',
						'version-bump.mjs',
					],
				},
			},
		},
	},
]);
